### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(event.x, event.y)?

### ISSUE THREAD

**Issue by roger656** [Linzertorte/ChineseChess#1]
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(event.x, event.y)?

**Comment by roger656** [comment]
i think you forgot the brakets

**Comment by Linzertorte** [comment]
Run it with python 2.

**Comment by roger656** [comment]
Thanks, but there is another problem. how do we move the peices?

**Comment by Linzertorte** [comment]
Just click it, it will show you the possible destination. then click one of the destinations.

**Comment by roger656** [comment]
ok thx
